spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

jwt:
  secret: ${JWT_SECRET}

aws:
  s3:
    bucket: ${AWS_S3_BUCKET}
    region: ${AWS_REGION:ap-northeast-2}

notification:
  slack:
    error-webhook-url: ${SLACK_ERROR_WEBHOOK_URL:}
    feedback-webhook-url: ${SLACK_FEEDBACK_WEBHOOK_URL:}

swagger:
  server-url: ${SWAGGER_SERVER_URL:}